### ISSUE TITLE
seems like the convert function had issue

### ISSUE THREAD

**Issue by stanosaka** [wxsms/bilibili-video2mp3#115]
see as running result below, thanks
npx bv2mp3 --url=https://www.bilibili.com/video/BV1yZ4y1X7v3
Fetching pages for: https://www.bilibili.com/video/BV1yZ4y1X7v3
7 [==============================] 100% 0.0s error 安稳最好啦
5 [==============================] 100% 0.0s error 日出日落
2 [==============================] 100% 0.0s error 海蓝色
3 [==============================] 100% 0.0s error 北戴河之歌
6 [==============================] 100% 0.0s error 元气女孩
8 [==============================] 100% 0.0s error 小小
1 [============                  ] 39% 32.5s downloading 口袋的天空
4 [==============================] 100% 0.0s error 知否知否
7 [==============================] 100% 0.0s error 安稳最好啦
2 [==============================] 100% 0.0s error 海蓝色
5 [==============================] 100% 0.0s error 日出日落
6 [==============================] 100% 0.0s error 元气女孩
8 [==============================] 100% 0.0s error 小小
3 [==============================] 100% 0.0s converting 北戴河之歌
7 [==============================] 100% 0.0s error 安稳最好啦
2 [==============================] 100% 0.0s error 海蓝色
4 [=======================       ] 77% 0.8s downloading 知否知否
6 [==============================] 100% 0.0s converting 元气女孩
5 [======================        ] 73% 0.5s downloading 日出日落^C

**Comment by wxsms** [comment]
pls run with `--debug`, it will generate a `bilibili-video2mp3-error.log` file in current dir. And patse it here.

**Comment by stanosaka** [comment]
sure, thanks.the content as follow:
index: 6
url: https://www.bilibili.com/video/BV1yZ4y1X7v3?p=6
Error: Command failed: node /home/szhou/node_modules/bv2mp3/src/_flv2mp3.js "元气女孩-湊-泠鸢hanserの小鹿包-2021-12-26.flv"
/home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.js:12
if(l){ra=oa?require("path").dirname(ra)+"/":__dirname+"/";ta=function(a,b){wa||(wa=require("fs"));xa||(xa=require("path"));a=xa.normalize(a);return wa.readFileSync(a,b?null:"utf8")};va=function(a){a=ta(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ka=process.argv[1].replace(/\\/g,"/"));ja=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ca))throw a;});process.on("unhandledRejection",u);la=function(a){process.exit(a)};f.inspect=
                                                                                                                                                                                                                                                                                                                                                                                                                                    ^

RuntimeError: abort(TypeError: Failed to parse URL from /home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.wasm). Build with -s ASSERTIONS=1 for more info.
    at process.u (/home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.js:25:109)
    at process.emit (node:events:511:28)
    at emit (node:internal/process/promises:150:20)
    at processPromiseRejections (node:internal/process/promises:284:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

Node.js v20.3.0

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:511:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)

index: 7
url: https://www.bilibili.com/video/BV1yZ4y1X7v3?p=7
Error: Command failed: node /home/szhou/node_modules/bv2mp3/src/_flv2mp3.js "安稳最好啦-湊-泠鸢hanserの小鹿包-2021-12-26.flv"
/home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.js:12
if(l){ra=oa?require("path").dirname(ra)+"/":__dirname+"/";ta=function(a,b){wa||(wa=require("fs"));xa||(xa=require("path"));a=xa.normalize(a);return wa.readFileSync(a,b?null:"utf8")};va=function(a){a=ta(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ka=process.argv[1].replace(/\\/g,"/"));ja=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ca))throw a;});process.on("unhandledRejection",u);la=function(a){process.exit(a)};f.inspect=
                                                                                                                                                                                                                                                                                                                                                                                                                                    ^

RuntimeError: abort(TypeError: Failed to parse URL from /home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.wasm). Build with -s ASSERTIONS=1 for more info.
    at process.u (/home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.js:25:109)
    at process.emit (node:events:511:28)
    at emit (node:internal/process/promises:150:20)
    at processPromiseRejections (node:internal/process/promises:284:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

Node.js v20.3.0

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:511:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)

index: 2
url: https://www.bilibili.com/video/BV1yZ4y1X7v3?p=2
Error: Command failed: node /home/szhou/node_modules/bv2mp3/src/_flv2mp3.js "海蓝色-湊-泠鸢hanserの小鹿包-2021-12-26.flv"
/home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.js:12
if(l){ra=oa?require("path").dirname(ra)+"/":__dirname+"/";ta=function(a,b){wa||(wa=require("fs"));xa||(xa=require("path"));a=xa.normalize(a);return wa.readFileSync(a,b?null:"utf8")};va=function(a){a=ta(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ka=process.argv[1].replace(/\\/g,"/"));ja=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ca))throw a;});process.on("unhandledRejection",u);la=function(a){process.exit(a)};f.inspect=
                                                                                                                                                                                                                                                                                                                                                                                                                                    ^

RuntimeError: abort(TypeError: Failed to parse URL from /home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.wasm). Build with -s ASSERTIONS=1 for more info.
    at process.u (/home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.js:25:109)
    at process.emit (node:events:511:28)
    at emit (node:internal/process/promises:150:20)
    at processPromiseRejections (node:internal/process/promises:284:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

Node.js v20.3.0

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:511:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)

index: 8
url: https://www.bilibili.com/video/BV1yZ4y1X7v3?p=8
Error: Command failed: node /home/szhou/node_modules/bv2mp3/src/_flv2mp3.js "小小-湊-泠鸢hanserの小鹿包-2021-12-26.flv"
/home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.js:12
if(l){ra=oa?require("path").dirname(ra)+"/":__dirname+"/";ta=function(a,b){wa||(wa=require("fs"));xa||(xa=require("path"));a=xa.normalize(a);return wa.readFileSync(a,b?null:"utf8")};va=function(a){a=ta(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ka=process.argv[1].replace(/\\/g,"/"));ja=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ca))throw a;});process.on("unhandledRejection",u);la=function(a){process.exit(a)};f.inspect=
                                                                                                                                                                                                                                                                                                                                                                                                                                    ^

RuntimeError: abort(TypeError: Failed to parse URL from /home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.wasm). Build with -s ASSERTIONS=1 for more info.
    at process.u (/home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.js:25:109)
    at process.emit (node:events:511:28)
    at emit (node:internal/process/promises:150:20)
    at processPromiseRejections (node:internal/process/promises:284:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

Node.js v20.3.0

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:511:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)

index: 5
url: https://www.bilibili.com/video/BV1yZ4y1X7v3?p=5
Error: Command failed: node /home/szhou/node_modules/bv2mp3/src/_flv2mp3.js "日出日落-湊-泠鸢hanserの小鹿包-2021-12-26.flv"
/home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.js:12
if(l){ra=oa?require("path").dirname(ra)+"/":__dirname+"/";ta=function(a,b){wa||(wa=require("fs"));xa||(xa=require("path"));a=xa.normalize(a);return wa.readFileSync(a,b?null:"utf8")};va=function(a){a=ta(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ka=process.argv[1].replace(/\\/g,"/"));ja=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ca))throw a;});process.on("unhandledRejection",u);la=function(a){process.exit(a)};f.inspect=
                                                                                                                                                                                                                                                                                                                                                                                                                                    ^

RuntimeError: abort(TypeError: Failed to parse URL from /home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.wasm). Build with -s ASSERTIONS=1 for more info.
    at process.u (/home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.js:25:109)
    at process.emit (node:events:511:28)
    at emit (node:internal/process/promises:150:20)
    at processPromiseRejections (node:internal/process/promises:284:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

Node.js v20.3.0

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:511:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)

index: 3
url: https://www.bilibili.com/video/BV1yZ4y1X7v3?p=3
Error: Command failed: node /home/szhou/node_modules/bv2mp3/src/_flv2mp3.js "北戴河之歌-湊-泠鸢hanserの小鹿包-2021-12-26.flv"
/home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.js:12
if(l){ra=oa?require("path").dirname(ra)+"/":__dirname+"/";ta=function(a,b){wa||(wa=require("fs"));xa||(xa=require("path"));a=xa.normalize(a);return wa.readFileSync(a,b?null:"utf8")};va=function(a){a=ta(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ka=process.argv[1].replace(/\\/g,"/"));ja=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ca))throw a;});process.on("unhandledRejection",u);la=function(a){process.exit(a)};f.inspect=
                                                                                                                                                                                                                                                                                                                                                                                                                                    ^

RuntimeError: abort(TypeError: Failed to parse URL from /home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.wasm). Build with -s ASSERTIONS=1 for more info.
    at process.u (/home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.js:25:109)
    at process.emit (node:events:511:28)
    at emit (node:internal/process/promises:150:20)
    at processPromiseRejections (node:internal/process/promises:284:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

Node.js v20.3.0

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:511:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:456:11)
    at Socket.emit (node:events:511:28)
    at Pipe.<anonymous> (node:net:334:12)

index: 6
url: https://www.bilibili.com/video/BV1yZ4y1X7v3?p=6
Error: Command failed: node /home/szhou/node_modules/bv2mp3/src/_flv2mp3.js "元气女孩-湊-泠鸢hanserの小鹿包-2021-12-26.flv"
/home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.js:12
if(l){ra=oa?require("path").dirname(ra)+"/":__dirname+"/";ta=function(a,b){wa||(wa=require("fs"));xa||(xa=require("path"));a=xa.normalize(a);return wa.readFileSync(a,b?null:"utf8")};va=function(a){a=ta(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ka=process.argv[1].replace(/\\/g,"/"));ja=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ca))throw a;});process.on("unhandledRejection",u);la=function(a){process.exit(a)};f.inspect=
                                                                                                                                                                                                                                                                                                                                                                                                                                    ^

RuntimeError: abort(TypeError: Failed to parse URL from /home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.wasm). Build with -s ASSERTIONS=1 for more info.
    at process.u (/home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.js:25:109)
    at process.emit (node:events:511:28)
    at emit (node:internal/process/promises:150:20)
    at processPromiseRejections (node:internal/process/promises:284:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

Node.js v20.3.0

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:511:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:456:11)
    at Socket.emit (node:events:511:28)
    at Pipe.<anonymous> (node:net:334:12)

index: 4
url: https://www.bilibili.com/video/BV1yZ4y1X7v3?p=4
Error: Command failed: node /home/szhou/node_modules/bv2mp3/src/_flv2mp3.js "知否知否-湊-泠鸢hanserの小鹿包-2021-12-26.flv"
/home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.js:12
if(l){ra=oa?require("path").dirname(ra)+"/":__dirname+"/";ta=function(a,b){wa||(wa=require("fs"));xa||(xa=require("path"));a=xa.normalize(a);return wa.readFileSync(a,b?null:"utf8")};va=function(a){a=ta(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ka=process.argv[1].replace(/\\/g,"/"));ja=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ca))throw a;});process.on("unhandledRejection",u);la=function(a){process.exit(a)};f.inspect=
                                                                                                                                                                                                                                                                                                                                                                                                                                    ^

RuntimeError: abort(TypeError: Failed to parse URL from /home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.wasm). Build with -s ASSERTIONS=1 for more info.
    at process.u (/home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.js:25:109)
    at process.emit (node:events:511:28)
    at emit (node:internal/process/promises:150:20)
    at processPromiseRejections (node:internal/process/promises:284:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

Node.js v20.3.0

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:511:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)

index: 7
url: https://www.bilibili.com/video/BV1yZ4y1X7v3?p=7
Error: Command failed: node /home/szhou/node_modules/bv2mp3/src/_flv2mp3.js "安稳最好啦-湊-泠鸢hanserの小鹿包-2021-12-26.flv"
/home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.js:12
if(l){ra=oa?require("path").dirname(ra)+"/":__dirname+"/";ta=function(a,b){wa||(wa=require("fs"));xa||(xa=require("path"));a=xa.normalize(a);return wa.readFileSync(a,b?null:"utf8")};va=function(a){a=ta(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ka=process.argv[1].replace(/\\/g,"/"));ja=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ca))throw a;});process.on("unhandledRejection",u);la=function(a){process.exit(a)};f.inspect=
                                                                                                                                                                                                                                                                                                                                                                                                                                    ^

RuntimeError: abort(TypeError: Failed to parse URL from /home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.wasm). Build with -s ASSERTIONS=1 for more info.
    at process.u (/home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.js:25:109)
    at process.emit (node:events:511:28)
    at emit (node:internal/process/promises:150:20)
    at processPromiseRejections (node:internal/process/promises:284:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

Node.js v20.3.0

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:511:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)

index: 2
url: https://www.bilibili.com/video/BV1yZ4y1X7v3?p=2
Error: Command failed: node /home/szhou/node_modules/bv2mp3/src/_flv2mp3.js "海蓝色-湊-泠鸢hanserの小鹿包-2021-12-26.flv"
/home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.js:12
if(l){ra=oa?require("path").dirname(ra)+"/":__dirname+"/";ta=function(a,b){wa||(wa=require("fs"));xa||(xa=require("path"));a=xa.normalize(a);return wa.readFileSync(a,b?null:"utf8")};va=function(a){a=ta(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ka=process.argv[1].replace(/\\/g,"/"));ja=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ca))throw a;});process.on("unhandledRejection",u);la=function(a){process.exit(a)};f.inspect=
                                                                                                                                                                                                                                                                                                                                                                                                                                    ^

RuntimeError: abort(TypeError: Failed to parse URL from /home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.wasm). Build with -s ASSERTIONS=1 for more info.
    at process.u (/home/szhou/node_modules/@ffmpeg/core/dist/ffmpeg-core.js:25:109)
    at process.emit (node:events:511:28)
    at emit (node:internal/process/promises:150:20)
    at processPromiseRejections (node:internal/process/promises:284:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

Node.js v20.3.0

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:511:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)

**Comment by wxsms** [comment]
https://github.com/ffmpegwasm/ffmpeg.wasm/issues/438 looks like it's a ffmpeg.wasm issue, it doesnt work with nodejs v18+. Maybe you should try node.js v16 at this time?

**Comment by stanosaka** [comment]
@wxsms  thank you, it works under v16.

**Comment by wxsms** [comment]
Welcome :D
